# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-13 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_author_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
